import { buildFileOperations } from "../plan/build.ts";
import { hashCanonical } from "../plan/canonical.ts";
import type { ManagedFileSnapshot, Operation } from "../plan/types.ts";
import type { FileChangesPullRequestConfiguration } from "../configuration/types.ts";
import type { PullRequestResult } from "../report/types.ts";
import { type GitHubClient, GitHubRequestError } from "./client.ts";
import { GitHubRepositoryStateSource } from "./rest_state_source.ts";

type FileOperation = Extract<Operation, {
  readonly type: "create-file" | "update-file" | "delete-file";
}>;

interface Commit {
  readonly sha: string;
  readonly message: string;
  readonly tree: { readonly sha: string };
  readonly parents: readonly { readonly sha: string }[];
}

interface PullRequest {
  readonly number: number;
  readonly html_url: string;
  readonly state: string;
  readonly title: string;
  readonly body: string | null;
  readonly head: {
    readonly ref: string;
    readonly sha: string;
    readonly repo: { readonly full_name: string } | null;
  };
  readonly base: {
    readonly ref: string;
    readonly repo: { readonly full_name: string };
  };
  readonly labels: readonly { readonly name: string }[];
}

const START = "<!-- octosmith:files:start -->";
const END = "<!-- octosmith:files:end -->";
const ZERO_OID = "0".repeat(40);

/** Refresh only the generated file list, or initialize a new pull request body. */
export function managedPullRequestBody(
  previous: string | null | undefined,
  operations: readonly FileOperation[],
  introduction = "",
): string {
  const changes = new Map(
    operations.map((operation) => [filePath(operation), operation]),
  );
  const section = [
    START,
    "### Modified files",
    "",
    ...[...changes.keys()].sort().map((path) => {
      const operation = changes.get(path)!;
      const action = operation.type === "create-file"
        ? "create"
        : operation.type === "update-file"
        ? "update"
        : "remove";
      const escaped = path.replace(
        /[&<>"'`*_~$\[\]\\\r\n\t]/g,
        (character) => "&#" + character.charCodeAt(0) + ";",
      );
      return "- <code>" + escaped + "</code> - " + action;
    }),
    "",
    "Generated by Octosmith.",
    END,
  ].join("\n");
  const body = previous ?? "";
  const starts = body.split(START).length - 1;
  const ends = body.split(END).length - 1;
  const tokens = body.split("octosmith:files:").length - 1;
  if (starts === 0 && ends === 0 && tokens === 0) {
    const prefix = previous === undefined ? introduction : body;
    if (previous === undefined && prefix.includes("octosmith:files:")) {
      throw new Error(
        "PR introduction must not contain Octosmith file markers",
      );
    }
    return prefix + (prefix.length > 0 ? "\n\n" : "") + section;
  }
  if (
    starts !== 1 || ends !== 1 || tokens !== 2 ||
    body.indexOf(START) > body.indexOf(END)
  ) {
    throw new Error("Invalid or duplicate Octosmith PR body markers");
  }
  return body.slice(0, body.indexOf(START)) + section +
    body.slice(body.indexOf(END) + END.length);
}

/** Reconcile one reserved branch and its owned pull request from complete desired state. */
export async function reconcileFilePullRequest(options: {
  readonly client: GitHubClient;
  readonly owner: string;
  readonly repository: string;
  readonly snapshot: ManagedFileSnapshot;
  readonly operations: readonly FileOperation[];
  readonly commitMessage: string;
  readonly settings: FileChangesPullRequestConfiguration;
  readonly allowClosure: boolean;
  readonly onPullRequest: (result: PullRequestResult) => void | Promise<void>;
}): Promise<void> {
  const { client, owner, repository, snapshot, settings } = options;
  const fullName = owner + "/" + repository;
  const repo = "/repos/" + encodeURIComponent(owner) + "/" +
    encodeURIComponent(repository);
  const branch = (settings.branchPrefix ?? "octosmith/") + "reconcile";
  if (branch === snapshot.branch) {
    throw new Error(
      "Managed file pull-request branch must not match target branch: " +
        branch,
    );
  }
  if (!validBranch(branch) || !validBranch(snapshot.branch)) {
    throw new Error("Invalid managed file branch name");
  }
  for (const file of snapshot.files) {
    if (
      !file.path || file.path.split("/").some((part) =>
        !part || part === "." || part === ".." || part.toLowerCase() === ".git"
      ) || file.path.includes("\0")
    ) {
      throw new Error("Invalid managed file path");
    }
  }
  const source = new GitHubRepositoryStateSource(client, owner);
  const assertTarget = async () => {
    if (
      await source.getBranchHead(repository, snapshot.branch) !==
        snapshot.baseSha
    ) {
      throw new Error("Managed file target changed since planning");
    }
  };
  await assertTarget();
  const files = await Promise.all(
    snapshot.files.map((file) =>
      source.getFile(repository, file.path, snapshot.baseSha)
    ),
  );
  const delta = buildFileOperations(
    files.filter((file) => file !== undefined),
    snapshot.files,
  );
  const sorted = (operations: readonly FileOperation[]) =>
    [...operations].sort((left, right) =>
      filePath(left) < filePath(right)
        ? -1
        : filePath(left) > filePath(right)
        ? 1
        : 0
    );
  if (
    (await hashCanonical(sorted(delta))).hash !==
      (await hashCanonical(sorted(options.operations))).hash
  ) {
    throw new Error(
      "Managed file operations do not match the complete desired-state delta",
    );
  }
  const body = managedPullRequestBody(undefined, delta, settings.introduction);
  const pulls = await client.get<readonly PullRequest[]>(repo + "/pulls", {
    state: "open",
    head: owner + ":" + branch,
    per_page: 100,
  });
  if (pulls.length > 1) {
    throw new Error("Ambiguous managed file pull request ownership");
  }
  let pull = pulls[0];
  const assertPull = (value: PullRequest, head?: string, state = "open") => {
    if (
      value.state !== state || value.head.ref !== branch ||
      value.head.repo?.full_name.toLowerCase() !== fullName.toLowerCase() ||
      value.base.ref !== snapshot.branch ||
      value.base.repo.full_name.toLowerCase() !== fullName.toLowerCase() ||
      (head !== undefined && value.head.sha !== head)
    ) {
      throw new Error("Managed file PR ownership or state changed");
    }
  };
  if (pull) {
    assertPull(pull);
    managedPullRequestBody(pull.body, delta);
  }
  if (delta.length === 0 && (!pull || !options.allowClosure)) {
    await assertTarget();
    return;
  }
  const branchRef = repo + "/git/ref/heads/" + encodePath(branch);
  const assertCurrent = async (expectedHead: string, locked = false) => {
    if (await source.getBranchHead(repository, branch) !== expectedHead) {
      throw new Error("Reconciliation branch changed concurrently");
    }
    if (
      locked &&
      await source.getBranchHead(repository, branch + "-lock") !== expectedHead
    ) {
      throw new Error("Reconciliation lock changed concurrently");
    }
    await assertTarget();
  };
  const existingRef = await client.request<
    { object: { sha: string } } | undefined
  >(
    "GET",
    branchRef,
    { allowNotFound: true },
  );
  const existing = existingRef === undefined
    ? undefined
    : await client.get<Commit>(
      repo + "/git/commits/" + existingRef.object.sha,
    );
  const ownership = "Octosmith-Reconciliation: " + fullName + ":" + branch;
  const ownedCommit = existing?.message.split("\n").includes(ownership) ??
    false;
  const ownedBody = pull?.body?.includes(START) ?? false;
  if ((existing && !ownedCommit && !ownedBody) || (pull && !existing)) {
    throw new Error(
      "Cannot establish ownership of reserved reconciliation branch",
    );
  }
  if (pull && existingRef) {
    assertPull(pull, existingRef.object.sha);
  }
  const message = render(options.commitMessage, owner, repository);
  const fingerprint =
    (await hashCanonical({ delta: sorted(delta), message })).hash;
  const trailer = "Octosmith-Delta: " + fingerprint;
  let head = existingRef?.object.sha;
  const branchCorrect = ownedCommit && existing?.parents.length === 1 &&
    existing.parents[0].sha === snapshot.baseSha &&
    existing.message.split("\n").includes(trailer) &&
    existing.message.split("\n").includes(
      "Octosmith-Tree: " + existing.tree.sha,
    );
  let completedAction: PullRequestResult["action"] | undefined;
  const recordCompletedAction = async (result: PullRequestResult) => {
    if (completedAction === undefined) {
      completedAction = result.action;
      await options.onPullRequest(result);
    }
  };
  const result = (
    value: PullRequest,
    action: "opened" | "updated",
  ): PullRequestResult => ({
    repository,
    number: value.number,
    url: value.html_url,
    action,
  });
  const title = render(
    settings.title ?? "Octosmith: reconcile managed files",
    owner,
    repository,
  );
  const assertMetadata = (value: PullRequest, includeLabels = false) => {
    if (
      value.title !== title ||
      value.body !== managedPullRequestBody(value.body, delta) ||
      includeLabels &&
        (settings.labels ?? []).some((label) =>
          !value.labels.some((current) => current.name === label)
        )
    ) {
      throw new Error("Managed file PR metadata changed concurrently");
    }
  };
  if (
    branchCorrect && pull && delta.length > 0 && pull.title === title &&
    pull.body === managedPullRequestBody(pull.body, delta) &&
    (settings.labels ?? []).every((label) =>
      pull.labels.some((current) => current.name === label)
    )
  ) {
    pull = await client.get<PullRequest>(repo + "/pulls/" + pull.number);
    assertPull(pull, head);
    if (
      pull.title === title &&
      pull.body === managedPullRequestBody(pull.body, delta) &&
      (settings.labels ?? []).every((label) =>
        pull.labels.some((current) => current.name === label)
      )
    ) {
      await assertCurrent(head!);
      return;
    }
  }
  const metadata = await client.get<{ node_id: string }>(repo);
  const updateRefs = async (
    refUpdates: readonly {
      name: string;
      beforeOid: string;
      afterOid: string;
      force: boolean;
    }[],
  ) => {
    const response = await client.request<
      { data?: { updateRefs: unknown }; errors?: readonly unknown[] }
    >(
      "POST",
      "/graphql",
      {
        body: {
          query:
            "mutation($input: UpdateRefsInput!) { updateRefs(input: $input) { clientMutationId } }",
          variables: { input: { repositoryId: metadata.node_id, refUpdates } },
        },
      },
    );
    if (response.errors?.length || !response.data?.updateRefs) {
      throw new Error(
        "Atomic reconciliation branch update rejected; target, reserved branch, or lock may have changed",
      );
    }
  };
  let nextHead = head!;
  if (!branchCorrect) {
    const base = await client.get<Commit>(
      repo + "/git/commits/" + snapshot.baseSha,
    );
    const nextTree = delta.length === 0
      ? base.tree
      : await client.request<{ sha: string }>(
        "POST",
        repo + "/git/trees",
        {
          body: {
            base_tree: base.tree.sha,
            tree: sorted(delta).map((operation) => ({
              path: filePath(operation),
              mode: "100644",
              type: "blob",
              ...(operation.type === "delete-file"
                ? { sha: null }
                : { content: operation.file.content }),
            })),
          },
        },
      );
    const commit = await client.request<{ sha: string }>(
      "POST",
      repo + "/git/commits",
      {
        body: {
          message: message + "\n\n" + ownership + "\n" + trailer +
            "\nOctosmith-Tree: " + nextTree.sha,
          tree: nextTree.sha,
          parents: [snapshot.baseSha],
        },
      },
    );
    nextHead = commit.sha;
  }
  const lock = "refs/heads/" + branch + "-lock";
  if (lock === "refs/heads/" + snapshot.branch) {
    throw new Error("Managed file lock branch must not match target branch");
  }
  await updateRefs([
    {
      name: "refs/heads/" + snapshot.branch,
      beforeOid: snapshot.baseSha,
      afterOid: snapshot.baseSha,
      force: false,
    },
    {
      name: "refs/heads/" + branch,
      beforeOid: head ?? ZERO_OID,
      afterOid: nextHead,
      force: !branchCorrect,
    },
    { name: lock, beforeOid: ZERO_OID, afterOid: nextHead, force: false },
  ]);
  head = nextHead;
  let reconciliationFailed = false;
  let reconciliationError: unknown;
  try {
    await assertCurrent(head, true);
    if (pull) {
      pull = await client.get<PullRequest>(repo + "/pulls/" + pull.number);
      assertPull(pull, head);
      const nextBody = managedPullRequestBody(pull.body, delta);
      await assertCurrent(head, true);
      if (delta.length === 0) {
        const closed = await client.request<PullRequest>(
          "PATCH",
          repo + "/pulls/" + pull.number,
          { body: { state: "closed" } },
        );
        assertPull(closed, head, "closed");
        await assertCurrent(head, true);
        await recordCompletedAction({
          repository,
          number: closed.number,
          url: closed.html_url,
          action: "closed",
          reason: "no_differences",
        });
      } else if (pull.body !== nextBody || pull.title !== title) {
        const updated = await client.request<PullRequest>(
          "PATCH",
          repo + "/pulls/" + pull.number,
          { body: { title, body: nextBody } },
        );
        assertPull(updated, head);
        assertMetadata(updated);
        await assertCurrent(head, true);
        pull = updated;
        await recordCompletedAction(result(updated, "updated"));
      } else if (!branchCorrect) {
        await recordCompletedAction(result(pull, "updated"));
      }
    } else {
      pull = await client.request<PullRequest>("POST", repo + "/pulls", {
        body: {
          title: render(
            settings.title ?? "Octosmith: reconcile managed files",
            owner,
            repository,
          ),
          head: branch,
          base: snapshot.branch,
          body,
        },
      });
      assertPull(pull, head);
      assertMetadata(pull);
      await assertCurrent(head, true);
      await recordCompletedAction(result(pull, "opened"));
    }
    const missingLabels = delta.length === 0
      ? []
      : [...new Set(settings.labels ?? [])].sort().filter((
        label,
      ) => !pull.labels.some((current) => current.name === label));
    if (missingLabels.length > 0) {
      pull = await client.get<PullRequest>(repo + "/pulls/" + pull.number);
      assertPull(pull, head);
      assertMetadata(pull);
      await assertCurrent(head, true);
      await client.request(
        "POST",
        repo + "/issues/" + pull.number + "/labels",
        { body: { labels: missingLabels } },
      );
      pull = await client.get<PullRequest>(repo + "/pulls/" + pull.number);
      assertPull(pull, head);
      assertMetadata(pull, true);
      await assertCurrent(head, true);
      await recordCompletedAction(result(pull, "updated"));
    }
  } catch (error) {
    reconciliationFailed = true;
    reconciliationError = error;
  }
  try {
    await updateRefs([{
      name: lock,
      beforeOid: nextHead,
      afterOid: ZERO_OID,
      force: false,
    }]);
  } catch (cleanupError) {
    const original = reconciliationError instanceof GitHubRequestError
      ? "GitHub managed-file reconciliation failed (HTTP " +
        reconciliationError.status + ")"
      : reconciliationError instanceof Error
      ? reconciliationError.message
      : "Managed-file reconciliation failed";
    throw new Error(
      (reconciliationFailed ? original + ". " : "") +
        "Reconciliation lock cleanup failed; inspect " + branch +
        "-lock before retrying",
      { cause: cleanupError },
    );
  }
  if (reconciliationFailed) throw reconciliationError;
  pull = await client.get<PullRequest>(repo + "/pulls/" + pull.number);
  assertPull(pull, head, completedAction === "closed" ? "closed" : "open");
  if (delta.length > 0) assertMetadata(pull, true);
  await assertCurrent(head);
}

function filePath(operation: FileOperation): string {
  return operation.type === "delete-file"
    ? operation.path
    : operation.file.path;
}

function encodePath(path: string): string {
  return path.split("/").map(encodeURIComponent).join("/");
}

function validBranch(branch: string): boolean {
  const hasControl = [...branch].some((character) =>
    character.charCodeAt(0) <= 32 || character.charCodeAt(0) === 127
  );
  return !hasControl && !/[~^:?*\[\\]/.test(branch) && !branch.includes("..") &&
    !branch.includes("@{") && branch !== "@" && !branch.endsWith(".") &&
    branch.split("/").every((part) =>
      part.length > 0 && !part.startsWith(".") && !part.endsWith(".lock")
    );
}

function render(value: string, owner: string, repository: string): string {
  return value.replaceAll("{organization}", owner).replaceAll(
    "{repository}",
    repository,
  );
}
