name: Request review

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read

jobs:
  request-review:
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        run: echo "Requesting review"
