name: OctoSmith validate

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: Kralizek/octosmith@v0
        with:
          mode: validate
          path: .
